### ISSUE TITLE
iris: Widen core widths and simplify model

### ISSUE THREAD

**Issue by ajvondrak** [DrItanium/syn#9]
I was just going over the code and noticed this.  I'm not sure whether or not it's a bug in the design.
1. Memory is byte-addressed: `core.memory` is a byte array, loads & stores move bytes to & from 16-bit addresses (thus spanning all 64k possible bytes).
2. Instructions, however, are 2 bytes each.
3. Thus, the program counter should step by 2 each clock cycle.

Yet jumps manipulate the program counter, potentially in really dangerous ways.  In long jumps, we give a 16-bit address (using two registers) to an arbitrary byte of memory, much like loads & stores.  Thus, a program can jump into the _middle_ of an instruction in memory.  Long jumps are clearly dangerous, but what'll ya do?  The addresses are very specific.

But then I was thinking that we _could_ do something about relative immediate jumps: when the user says `goto +1`, do they really mean to increment the PC by one _byte_, or by one _instruction_?  Right now it just does a straight `proc->pc += get_jump_immediate(...)` (modulo signing).  So if I want to skip forward by `n` instructions, I'd always have to say `goto 2n`.  If I jumped by an odd number, I'd probably wind up in the middle of an instruction.  (Though, of course, that depends on the instructions being tightly packed in memory.)

I dunno.  It seems like this is probably a common trait of architectures the world over that I'm just not aware of.  Is this the sort of thing that warrants semantic changes, or is it the sort of thing that just warrants a warning label?

**Comment by ajvondrak** [comment]
@DrItanium Had cause to look through my github repos, wound up on a sentimental journey reading through these old issues. All I could think was: wow, me from almost 4 years ago sounds _way_ smarter than present me, because I have no idea what he's talking about. :joy:

**Comment by DrItanium** [comment]
@ajvondrak holy crap I forgot about this thread 😋
